// Facts
const facts = [
  "Octopi have 3 hearts.",
  "The brain is the most active when you are asleep.",
  "The speed if information coming through your nerves is about 248 miles an hour.",
  "Humans are the only species that have adapted the ability to blush.",
  "Your left lung is approximately 10% smaller than your right due to the size of the human heart.",
  "During your lifetime, a human spends 5 years eating.",
  "The skin of an adult person weighs aproximately 3 to 4 kgs.",
  "It is the sign of a healthy mind when you hear your name when nobody is calling.",
  "Vaccines play a significant role in educating your immune system.",
  "Chewing gum while studying can help boost your memory.",
  "Drinking 500ml of cole water can boost your metabolism by 30% on an empty stomach.",
  "In camera terms, the average human eye is around 576 megapixels.",
  "Exercising regularly, positive feelings, and eating habits may all boost your immunity.",
  "A healthy adult human heart beats around 80 times in a minute.",
  "Your heart rate changes to the music you listen to.",
  "We experience billions of germs everyday, but not all of them are bad.",
  "Your thumb is the same length as your nose.",
  "Side sleeping can lower back pain.",
  "The brain is one of the fattest organs, which contains about 60% is fat.",
  "Male brains are typically 8-13% larger than female brains.",
  "Some people can hear their eyeballs move around in their minds.",
  "Most dreams only last about 5-20 minutes.",
  "Brushing your teeth with your opposite hand stimulates the brain 's cognitive and creative functions.",
  "You will have about 70,000 thoughts in a day.",
  "The ears have the smallest bones in your body.",
  "Light from the sun is actually made from every color of the rainbow.",
  "Cockroaches can live a week without their heads.",
  "The blue whale is the biggest mammal in the Animalia kingdom.",
  "Pigeons were believed to be the first bird to deliver messages.",
  "The Atlas Moth is the largest insect in the world, with a wing span of 12 inches.",
  "Octopi are fast swimmers, but they prefer to crawl because the heart stops delivering blood and they get exhausted.",
  "Octopi have good camouflage, which could change their body color to their surroundings in milliseconds.",
  "Octopi are a highly intelligent marine species, because they have the largest brain in the ocean.",
  "Octopi can use tools in order to escape from their prey.",
  "Humans grow a half inch every day due to fluids being released during the day.",
  "Your brain stops growing after the age of 18 years old, and it never stops working, even when sleeping.",
  "Humans have less bones than we have than when we are born, with them fusing over time to 206.",
  "Your heart beats so fast it could squirt blood about 30 feet.",
  "Human skin is the only organ you should be able to touch.",
  "Your brain can finish an electrical circut and light a lightbulb.",
  "Jellyfish mostly comprise of water, that ration being 98%",
  "The snapping shrimp is one of the loudest known creatures, which is due to them being able to shoot jets of water at up to 62 miles per hour.",
  "A snapping shrimps bubble vapor explodes at 200 decibels, enough to stun and even kill it's prey.",
  "A flamingo can only eat with it's head upside down.",
  "An albatross can travel up to 10,000 miles in a single journey, and circumnavigate the world in 46 days.",
  "Baby giraffes can stand up a half hour after being born.",
  "Cows have different areas and herds have different accents to their moo.",
  "A dog's noseprint is as unique as a humans finger print, so it can be used to identify a specific dog.",
  "The leg bones of a bat are so thin that none can walk.",
  "There are 1 million ants for every human in the world."
]

const date = new Date();

document.getElementById("myDiv").innerHTML = facts[date.getDay()];